### ISSUE TITLE
Group names with space

### ISSUE THREAD

**Issue by joneswac** [saz/puppet-sudo#262]
**Version:** saz-sudo (v6.0.0)

This issue affects Active Directory (or other LDAP) joined machines.

When setting a config with content that includes a group name with space in it there is a parsing error during the Puppet run.
**Example code**:
```
  'space-group':
    content: "%group\ with\ space     ALL=(ALL)   ALL"
    priority: 20
```
**Puppet run error**
```
Notice: /Stage[main]/Sudo/Sudo::Conf[space-group]/Exec[sudo-syntax-check for file/etc/sudoers.d/20_space-group]/returns: parse error in /etc/sudoers.d/20_space-group near line 2
```
The content portion of this _works_ in RHEL/CentOS 7 -- I'm not sure if that's a caveat to those OSes or standard Linux. Here's a forum from RedHat where I found this answer. https://access.redhat.com/discussions/2950661

**Comment by zilchms** [comment]
Can you specify on what OS your agent is running into this issue? Helps me trying to replicate this.

**Comment by joneswac** [comment]
The issue was experienced on CentOS Linux release 7.9.2009 (Core); if it matters Puppet agent version 5.5.22.

**Comment by saz** [comment]
I don't see a good way to solve this issue. `content` is just a string. I don't see any way to escape just the group part within it.

**Comment by zilchms** [comment]
If I read this correctly it starts somewhere around here:
https://github.com/saz/puppet-sudo/blob/f3cecf49ecde3dd81269a0c20cc6b68fcc212c34/manifests/conf.pp#L105
Resulting in:
https://github.com/saz/puppet-sudo/blob/f3cecf49ecde3dd81269a0c20cc6b68fcc212c34/manifests/conf.pp#L139
beeing called.
Can you manually try to replicate the full check with the "||" and the part after? Though I dont see, why that should be an issue, since manually calling visudo -c seems to work for you.

**Comment by saz** [comment]
I'm trying to clean up issues and as this issue is pretty old and not much activity is happening here, I'll close it.

Feel free to open it again, if needed.
